<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model {
	//
	public function delete() {
		@unlink( storage_path( 'app/gallery/' . $this->image ) );

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
