<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Cviebrock\EloquentSluggable\Sluggable;

class Project extends Model implements TranslatableContract {
	use Translatable, Sluggable;

	public $translatedAttributes = [ 'name', 'subtitle', 'description', 'developer_company', 'indirect_sales', 'payment_methods' ];

	protected $fillable = [
		'category_id',
        'slug',
		'region_id',
		'video_link',
		'image',
		'min_price',
		'min_space',
		'max_price',
		'max_space',
		'map'
	];

	/**
	 * Return the sluggable configuration array for this model.
	 *
	 * @return array
	 */
	public function sluggable() {
		return [
			'slug' => [
				'source' => 'name'
			]
		];
	}

	public function images() {
		return $this->hasMany( ProjectGallery::class );
	}

    public function region()
    {
        return $this->belongsTo(Region::class);
	}

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

	public function delete() {
	    $this->deleteTranslations();
		@unlink( storage_path( 'app/projects/' . $this->image ) );
		foreach ( $this->images() as $image ) {
			@unlink( storage_path( 'app/projects/' . $image->image ) );
			$image->delete();
		}

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
