<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProjectGallery extends Model {
	//
	protected $fillable = [ 'image' ];

	public function delete() {
		@unlink( storage_path( 'app/projects/' . $this->image ) );

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
