<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Testimonial extends Model implements TranslatableContract {
	use Translatable;

	public $translatedAttributes = [ 'name', 'position', 'description' ];

	protected $fillable = [ 'image' ];

	public function delete() {
		$this->deleteTranslations();
		@unlink( storage_path( 'app/testimonials/' . $this->image ) );

		return parent::delete(); // TODO: Change the autogenerated stub
	}
}